# Generated by Django 4.0.5 on 2022-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mers',
            options={'verbose_name': 'Мерс'},
        ),
        migrations.AddField(
            model_name='mers',
            name='color',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mers',
            name='year',
            field=models.CharField(default=11, max_length=15),
            preserve_default=False,
        ),
    ]
