# Generated by Django 4.0.5 on 2022-06-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_bmw_alter_mers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmw',
            name='image',
            field=models.ImageField(default=11, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mers',
            name='image',
            field=models.ImageField(default=21, upload_to='', verbose_name='image.mers'),
            preserve_default=False,
        ),
    ]
