# Generated by Django 4.0.5 on 2022-06-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_bmw_image_mers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmw',
            name='image1',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
