# Generated by Django 4.0.5 on 2022-06-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_mersedes_benz_delete_mers_remove_bmw_image1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mersedes_benz',
            options={'verbose_name': 'Mersedes-Benz', 'verbose_name_plural': 'Mersedes-Benz'},
        ),
        migrations.AddField(
            model_name='bmw',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mersedes_benz',
            name='description',
            field=models.CharField(default=3, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mersedes_benz',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
