# Generated by Django 4.0.5 on 2022-06-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_alter_mersedes_benz_options_bmw_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('color', models.CharField(max_length=25)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'Audi',
                'verbose_name_plural': 'Audi',
            },
        ),
        migrations.AlterField(
            model_name='bmw',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mersedes_benz',
            name='description',
            field=models.TextField(),
        ),
    ]
