# Generated by Django 4.0.5 on 2022-06-09 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_audi_alter_bmw_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('color', models.CharField(max_length=25)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='image')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
            ],
            options={
                'verbose_name': 'Audi',
                'verbose_name_plural': 'Audi',
            },
        ),
        migrations.DeleteModel(
            name='Audi',
        ),
        migrations.DeleteModel(
            name='BMW',
        ),
        migrations.DeleteModel(
            name='Mersedes_Benz',
        ),
    ]
